In [45]:
from sklearn.datasets import make_regression
import pandas as pd 
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score



In [46]:
X,y = make_regression(n_samples=100,n_features=2,n_informative=2, n_targets=1,noise=50)

In [47]:
X

array([[-3.81659636e-01,  4.40234165e-01],
       [-1.64432893e+00,  1.69273551e+00],
       [-4.16238118e-01, -5.49174310e-01],
       [-6.66336187e-01,  1.39647335e-01],
       [ 1.13141252e+00, -1.42172273e+00],
       [-3.02719907e-01,  5.62110867e-01],
       [ 1.21560475e-01, -1.17135520e+00],
       [ 3.33006266e-01,  1.06785869e+00],
       [-9.43661854e-01,  6.62405260e-02],
       [ 6.25860710e-01, -8.81644615e-02],
       [ 3.94851798e-01, -1.00898599e-01],
       [ 2.72829282e-01,  1.45370102e-01],
       [-2.64954437e+00, -5.11132858e-01],
       [-2.18805147e+00,  5.20410240e-01],
       [-1.48587116e+00,  6.53115603e-01],
       [ 1.22140340e+00, -1.19809746e+00],
       [ 6.75208430e-01,  1.41052176e+00],
       [ 6.50830107e-01,  1.12829494e+00],
       [ 1.12653169e-01,  2.11209616e+00],
       [ 4.19350722e-01, -4.66373011e-01],
       [ 2.11315772e+00,  3.28853540e-01],
       [ 8.34200762e-01, -3.40828841e-03],
       [-4.76945277e-01,  7.21120029e-01],
       [-1.

In [48]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [49]:
df

feature1  feature2      target
0  -0.381660  0.440234  109.357015
1  -1.644329  1.692736  -34.902703
2  -0.416238 -0.549174   33.217744
3  -0.666336  0.139647  -52.232545
4   1.131413 -1.421723  -45.700080
..       ...       ...         ...
95  1.602194  1.048884   37.883091
96 -0.187541  0.975991   65.397118
97 -1.199431  0.607271   17.128204
98 -0.506543  1.212837  -37.673792
99  0.929467 -0.741729   -0.822463

[100 rows x 3 columns]

In [50]:
df.shape

(100, 3)

In [51]:
df.head()

feature1  feature2      target
0 -0.381660  0.440234  109.357015
1 -1.644329  1.692736  -34.902703
2 -0.416238 -0.549174   33.217744
3 -0.666336  0.139647  -52.232545
4  1.131413 -1.421723  -45.700080

In [52]:
fig = px.scatter_3d(df,x='feature1',y='feature2',z='target')

fig.show()

In [53]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=4)

In [54]:
from sklearn.linear_model import LinearRegression

In [55]:
lr = LinearRegression()

In [56]:
lr.fit(X_train,y_train)

LinearRegression()

In [57]:
y_pred = lr.predict(X_test)

In [58]:
y_pred

array([  43.51575795,    5.68097897,   27.26958521,   52.42363507,
        -52.05158193,   -0.60215186,   39.34197392,    1.73397244,
         63.78923888,    7.09266593,   12.71949216,  -19.08618361,
         56.12946412, -133.38901612,  -15.51932204,  -46.68333725,
         -1.26612539,  -11.92172246,  -24.0963165 ,   38.30767975,
         12.11373137,  -20.46459037,  -21.93540134,   21.24279805,
         22.97820555])

In [59]:
print("y_pred",y_pred)

y_pred [  43.51575795    5.68097897   27.26958521   52.42363507  -52.05158193
   -0.60215186   39.34197392    1.73397244   63.78923888    7.09266593
   12.71949216  -19.08618361   56.12946412 -133.38901612  -15.51932204
  -46.68333725   -1.26612539  -11.92172246  -24.0963165    38.30767975
   12.11373137  -20.46459037  -21.93540134   21.24279805   22.97820555]


In [60]:
X_test

array([[ 2.11315772,  0.32885354],
       [ 0.3948518 , -0.1008986 ],
       [-0.18754058,  0.97599148],
       [ 0.67520843,  1.41052176],
       [-1.64247483, -1.06778685],
       [ 1.05095307, -0.67325994],
       [ 0.22630887,  1.18465449],
       [-1.19943079,  0.60727063],
       [ 0.80951152,  1.7428349 ],
       [-0.80378376,  0.5871047 ],
       [-0.78180566,  0.77531157],
       [-0.41623812, -0.54917431],
       [ 1.60219448,  1.04888439],
       [-0.8604148 , -4.37360706],
       [-2.18805147,  0.52041024],
       [-1.04459664, -1.19523024],
       [-1.48587116,  0.6531156 ],
       [-0.70896645, -0.13887018],
       [-0.45997677, -0.70389229],
       [ 0.91953309,  0.77901201],
       [-0.47702232,  0.59160125],
       [ 1.13141252, -1.42172273],
       [ 0.07986806, -0.91439915],
       [ 2.94172431, -0.90335031],
       [ 0.24469485,  0.59352006]])

In [61]:
print("mse",mean_squared_error(y_test,y_pred))

mse 2126.22758652092


In [62]:
print("mae",mean_absolute_error(y_test,y_pred))

mae 36.24874342597346


In [63]:
print("R2 score",r2_score(y_test,y_pred))

R2 score 0.4503435852170504


In [64]:

final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

In [65]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)

z_final = lr.predict(final).reshape(10,10)

z = z_final

final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

In [66]:
fig = px.scatter_3d(df,x='feature1',y='feature2', z='target')

fig.add_trace(go.Surface(x=x,y=y,z=z))

fig.show()

In [67]:
lr.coef_

array([14.978809 , 28.1478593])

In [68]:
lr.intercept_

2.606648863200858